import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8FAFC' },
  centered: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 32, backgroundColor: '#F8FAFC' },
  errorIcon: { fontSize: 64, marginBottom: 16 },
  errorTitle: { color: '#1E293B', fontSize: 22, fontWeight: '700', marginBottom: 8 },
  errorText: { color: '#64748B', fontSize: 14 },

  header: { padding: 24, paddingTop: 32 },
  retailerRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 16 },
  retailerLogo: { fontSize: 40 },
  retailerName: { color: '#FFFFFF', fontSize: 16, fontWeight: '700' },
  orderId: { color: '#E0F2FE', fontSize: 13, marginTop: 2, opacity: 0.8 },
  productName: { color: '#FFFFFF', fontSize: 18, fontWeight: '600', marginBottom: 12 },
  statusBadge: {
    flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFFFFF',
    alignSelf: 'flex-start', borderRadius: 20, paddingHorizontal: 12, paddingVertical: 6,
    gap: 6, marginBottom: 10,
    shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.1, shadowRadius: 2, elevation: 1,
  },
  statusDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#006EB7' },
  statusText: { color: '#006EB7', fontSize: 13, fontWeight: '700' },
  deliveryRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  deliveryText: { color: '#E0F2FE', fontSize: 14 },

  liveCard: {
    margin: 16, backgroundColor: '#FFFFFF', borderRadius: 16,
    padding: 18, borderWidth: 1, borderColor: '#E2E8F0',
    shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.05, shadowRadius: 4, elevation: 2,
  },
  liveIndicator: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 8 },
  liveDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#006EB7' },
  liveLabel: { color: '#006EB7', fontSize: 11, fontWeight: '800', letterSpacing: 1 },
  liveTitle: { color: '#1E293B', fontSize: 16, fontWeight: '700', marginBottom: 4 },
  liveDescription: { color: '#64748B', fontSize: 14, lineHeight: 20, marginBottom: 8 },
  liveLocationRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  liveLocation: { color: '#006EB7', fontSize: 13 },

  mapButton: {
    marginHorizontal: 16, marginBottom: 16, borderRadius: 16, overflow: 'hidden',
    shadowColor: '#006EB7', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.2, shadowRadius: 8, elevation: 4,
  },
  mapButtonGradient: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    padding: 18, gap: 12,
  },
  mapButtonLeft: { flexDirection: 'row', alignItems: 'center', gap: 14, flex: 1 },
  mapButtonEmoji: { fontSize: 32 },
  mapButtonTitle: { color: '#FFFFFF', fontSize: 15, fontWeight: '700' },
  mapButtonSubtitle: { color: '#E0F2FE', fontSize: 12, marginTop: 2 },

  progressSection: { marginHorizontal: 16, marginBottom: 8 },
  progressBar: { height: 6, backgroundColor: '#E2E8F0', borderRadius: 3, overflow: 'hidden', marginBottom: 6 },
  progressFill: { height: '100%', backgroundColor: '#006EB7', borderRadius: 3 },
  progressText: { color: '#94A3B8', fontSize: 12, textAlign: 'right' },

  timeline: { margin: 16 },
  timelineTitle: { color: '#1E293B', fontSize: 16, fontWeight: '700', marginBottom: 16 },
  timelineItem: { flexDirection: 'row', gap: 12 },
  timelineLeft: { alignItems: 'center', width: 28 },
  timelineDot: {
    width: 28, height: 28, borderRadius: 14, backgroundColor: '#FFFFFF',
    alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderColor: '#CBD5E1', zIndex: 1,
  },
  dotCompleted: { backgroundColor: '#006EB7', borderColor: '#006EB7' },
  dotActive: { backgroundColor: '#FFFFFF', borderColor: '#006EB7' },
  dotPending: { backgroundColor: '#F8FAFC', borderColor: '#E2E8F0' },
  dotInner: { width: 10, height: 10, borderRadius: 5, backgroundColor: '#006EB7' },
  timelineLine: { width: 2, flex: 1, backgroundColor: '#E2E8F0', marginVertical: 2 },
  lineCompleted: { backgroundColor: '#006EB7' },
  timelineContent: { flex: 1, paddingBottom: 20 },
  contentPending: { opacity: 0.5 },
  timelineRow: { flexDirection: 'row', gap: 10 },
  timelineEventIcon: { fontSize: 22, marginTop: 2 },
  timelineTextArea: { flex: 1 },
  timelineEventTitle: { color: '#1E293B', fontSize: 14, fontWeight: '700', marginBottom: 3 },
  textPending: { color: '#94A3B8' },
  textActive: { color: '#006EB7' },
  timelineEventDesc: { color: '#64748B', fontSize: 13, lineHeight: 18, marginBottom: 4 },
  timelineLocationRow: { flexDirection: 'row', alignItems: 'center', gap: 3, marginBottom: 2 },
  timelineLocation: { color: '#94A3B8', fontSize: 12 },
  timelineTimestamp: { color: '#94A3B8', fontSize: 11 },
  timelineIotBadge: {
    flexDirection: 'row', alignItems: 'center',
    backgroundColor: '#F1F5F9', paddingHorizontal: 6, paddingVertical: 2,
    borderRadius: 4, marginTop: 4, marginBottom: 6, alignSelf: 'flex-start', gap: 4,
  },
  timelineIotText: { fontSize: 10, fontWeight: '700', color: '#475569' },
  timelineIotDivider: { width: 1, height: 8, backgroundColor: '#CBD5E1', marginHorizontal: 2 },

  supplySection: { marginHorizontal: 16, marginBottom: 20 },
  supplySectionTitle: { color: '#1E293B', fontSize: 16, fontWeight: '700', marginBottom: 6 },
  supplySectionSubtitle: { color: '#64748B', fontSize: 13, marginBottom: 16, lineHeight: 18 },
  supplySteps: {
    flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFFFFF',
    borderRadius: 14, padding: 16, gap: 4, borderWidth: 1, borderColor: '#E2E8F0',
    shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05, shadowRadius: 2, elevation: 1,
  },
  supplyStep: { flex: 1, alignItems: 'center' },
  supplyStepEmoji: { fontSize: 22, marginBottom: 4 },
  supplyStepTitle: { color: '#334155', fontSize: 10, fontWeight: '700', textAlign: 'center' },
  supplyStepDesc: { color: '#94A3B8', fontSize: 9, textAlign: 'center', marginTop: 2 },
  supplyArrow: { color: '#CBD5E1', fontSize: 14 },

  iotSection: { marginHorizontal: 16, marginBottom: 20 },
  iotTitle: { color: '#1E293B', fontSize: 16, fontWeight: '700', marginBottom: 4 },
  iotSubtitle: { color: '#64748B', fontSize: 12, marginBottom: 14 },
  iotCard: {
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
    borderRadius: 12, padding: 14, marginBottom: 10, borderWidth: 1,
    shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05, shadowRadius: 2, elevation: 1,
  },
  iotOk: { backgroundColor: '#F0FDF4', borderColor: '#BBF7D0' },
  iotAlert: { backgroundColor: '#FEF2F2', borderColor: '#FECACA' },
  iotCardLeft: { flexDirection: 'row', alignItems: 'center', gap: 10, flex: 1 },
  iotIcon: { fontSize: 22 },
  iotLocation: { color: '#1E293B', fontSize: 13, fontWeight: '600' },
  iotTime: { color: '#64748B', fontSize: 11, marginTop: 2 },
  iotCardRight: { alignItems: 'flex-end', gap: 4 },
  iotTemp: { fontSize: 20, fontWeight: '800' },
  iotTarget: { color: '#64748B', fontSize: 11 },
  iotBadge: { borderRadius: 6, paddingHorizontal: 8, paddingVertical: 2, borderWidth: 1 },
  iotBadgeOk: { borderColor: '#10B981', backgroundColor: '#DCFCE7' },
  iotBadgeAlert: { borderColor: '#EF4444', backgroundColor: '#FEE2E2' },
  iotBadgeText: { fontSize: 11, fontWeight: '700' },
  iotSensorSmallBadge: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 4 },
  iotSensorSmallText: { fontSize: 11, color: '#64748B', fontWeight: '500' },

  actions: { marginHorizontal: 16, gap: 10 },
  actionBtn: {
    flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFFFFF',
    borderRadius: 12, padding: 16, gap: 12, borderWidth: 1, borderColor: '#E2E8F0',
    shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05, shadowRadius: 2, elevation: 1,
  },
  actionBtnActive: { borderColor: '#006EB7', backgroundColor: '#F0F9FF' },
  mapActionBtn: {
    flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFFFFF',
    borderRadius: 12, padding: 16, gap: 12, borderWidth: 1, borderColor: '#E2E8F0',
    shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05, shadowRadius: 2, elevation: 1,
  },
  actionTextBlock: { flex: 1 },
  actionText: { color: '#006EB7', fontSize: 14, fontWeight: '600' },
  actionSubtext: { color: '#64748B', fontSize: 11, marginTop: 2 },
});
