import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8FAFC' },
  centered: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 32, backgroundColor: '#F8FAFC' },
  loadingText: { color: '#64748B', fontSize: 16, marginTop: 16 },
  loadingSubtext: { color: '#94A3B8', fontSize: 13, marginTop: 6 },
  errorIcon: { fontSize: 64, marginBottom: 16 },
  errorTitle: { color: '#1E293B', fontSize: 22, fontWeight: '700', marginBottom: 8 },
  errorText: { color: '#64748B', fontSize: 15, textAlign: 'center', marginBottom: 8 },
  errorBarcode: { color: '#94A3B8', fontSize: 13 },
  retryBtn: { marginTop: 20, backgroundColor: '#006EB7', paddingHorizontal: 24, paddingVertical: 12, borderRadius: 12 },
  retryText: { color: '#fff', fontWeight: '600' },

  // Recall Banner
  recallBanner: { margin: 12, borderRadius: 14, padding: 16, borderWidth: 2 },
  recallCritical: { backgroundColor: '#FEF2F2', borderColor: '#EF4444' },
  recallWarning: { backgroundColor: '#FFFBEB', borderColor: '#F59E0B' },
  recallIconRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 12, marginBottom: 10 },
  recallIcon: { fontSize: 28 },
  recallTextBlock: { flex: 1 },
  recallTitle: { color: '#1E293B', fontSize: 16, fontWeight: '900' },
  recallId: { color: '#64748B', fontSize: 11, marginTop: 2 },
  recallReason: { color: '#475569', fontSize: 13, lineHeight: 18, marginBottom: 10 },
  recallActionBox: { flexDirection: 'row', alignItems: 'flex-start', gap: 8, backgroundColor: 'rgba(0,0,0,0.05)', borderRadius: 8, padding: 10, marginBottom: 8 },
  recallAction: { color: '#1E293B', fontSize: 13, flex: 1, lineHeight: 18 },
  recallAuthority: { color: '#64748B', fontSize: 11 },
  aiBadgeRow: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 8 },
  aiBadgeText: { fontSize: 10, fontWeight: '700', textTransform: 'uppercase' },

  // Header
  header: { padding: 24, alignItems: 'center', paddingTop: 32, borderBottomWidth: 1, borderBottomColor: '#E2E8F0' },
  productImage: { width: 160, height: 160, marginBottom: 16, borderRadius: 12 },
  imagePlaceholder: { width: 160, height: 160, backgroundColor: '#F1F5F9', borderRadius: 12, alignItems: 'center', justifyContent: 'center', marginBottom: 16, borderWidth: 1, borderColor: '#E2E8F0' },
  imagePlaceholderText: { fontSize: 64 },
  productName: { fontSize: 20, fontWeight: '800', color: '#1E293B', textAlign: 'center', marginBottom: 4 },
  brand: { fontSize: 14, color: '#64748B', marginBottom: 4 },
  barcode: { fontSize: 12, color: '#94A3B8' },
  lotBadge: { backgroundColor: '#7C3AED', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 6, marginTop: 4 },
  lotLabel: { color: '#FFFFFF', fontSize: 11, fontWeight: '700' },

  // Journey Section
  journeyCard: { backgroundColor: '#FFFFFF', borderRadius: 16, padding: 16, borderWidth: 1, borderColor: '#DDD6FE', shadowColor: '#7C3AED', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.1, shadowRadius: 8, elevation: 3 },
  journeyHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 20, borderBottomWidth: 1, borderBottomColor: '#F3F4F6', paddingBottom: 12 },
  journeyLotTitle: { fontSize: 11, color: '#6B7280', textTransform: 'uppercase', fontWeight: '600' },
  journeyLotValue: { fontSize: 16, fontWeight: '800', color: '#1F2937' },
  verifiedBadge: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: '#ECFDF5', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8 },
  verifiedText: { color: '#059669', fontSize: 12, fontWeight: '700' },

  timeline: { paddingLeft: 8 },
  timelineItem: { flexDirection: 'row', minHeight: 70 },
  timelineLeft: { width: 40, alignItems: 'center' },
  timelinePoint: { width: 32, height: 32, borderRadius: 16, backgroundColor: '#F3F4F6', alignItems: 'center', justifyContent: 'center', zIndex: 1, borderWidth: 2, borderColor: '#DDD6FE' },
  timelineIcon: { fontSize: 16 },
  timelineLine: { position: 'absolute', top: 32, bottom: 0, width: 2, backgroundColor: '#DDD6FE' },
  timelineRight: { flex: 1, paddingLeft: 12, paddingBottom: 20 },
  timelineEvent: { fontSize: 15, fontWeight: '700', color: '#1F2937' },
  timelineLocation: { fontSize: 13, color: '#4B5563', marginTop: 2 },
  timelineStepDate: { fontSize: 11, color: '#9CA3AF', marginTop: 4 },
  rescanBatchBtn: { alignSelf: 'center', marginTop: 10, padding: 8 },
  rescanBatchText: { color: '#7C3AED', fontSize: 13, fontWeight: '600', textDecorationLine: 'underline' },

  noJourneyCard: { backgroundColor: '#F8FAFC', borderRadius: 16, padding: 24, alignItems: 'center', borderStyle: 'dotted', borderWidth: 2, borderColor: '#CBD5E1' },
  noJourneyIconBox: { width: 64, height: 64, borderRadius: 32, backgroundColor: '#F1F5F9', alignItems: 'center', justifyContent: 'center', marginBottom: 16 },
  noJourneyTitle: { fontSize: 16, fontWeight: '700', color: '#475569', marginBottom: 8 },
  noJourneyText: { fontSize: 13, color: '#64748B', textAlign: 'center', lineHeight: 20, marginBottom: 20 },
  batchScanBtn: { shadowColor: '#7C3AED', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 8, elevation: 4 },
  batchScanGradient: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 20, paddingVertical: 12, borderRadius: 12 },
  batchScanText: { color: '#fff', fontSize: 15, fontWeight: '700' },

  // Camera
  cameraContainer: { flex: 1, backgroundColor: '#000' },
  camera: { flex: 1 },
  cameraOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0,0,0,0.4)', justifyContent: 'center', alignItems: 'center' },
  scanTarget: { width: 280, height: 180, position: 'relative' },
  scanCorner: { position: 'absolute', width: 40, height: 40, borderColor: '#7C3AED', borderWidth: 4 },
  topLeft: { top: 0, left: 0, borderRightWidth: 0, borderBottomWidth: 0 },
  topRight: { top: 0, right: 0, borderLeftWidth: 0, borderBottomWidth: 0 },
  bottomLeft: { bottom: 0, left: 0, borderRightWidth: 0, borderTopWidth: 0 },
  bottomRight: { bottom: 0, right: 0, borderLeftWidth: 0, borderTopWidth: 0 },
  scanInstruction: { color: '#fff', fontSize: 15, fontWeight: '600', textAlign: 'center', marginTop: 40, paddingHorizontal: 40, textShadowColor: 'rgba(0,0,0,0.8)', textShadowOffset: { width: 1, height: 1 }, textShadowRadius: 4 },
  cameraButtons: { position: 'absolute', bottom: 60, width: '100%', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around' },
  closeCamera: { padding: 10 },
  captureBtn: { width: 80, height: 80, alignItems: 'center', justifyContent: 'center' },
  captureBtnOuter: { width: 70, height: 70, borderRadius: 35, borderWidth: 4, borderColor: '#fff', alignItems: 'center', justifyContent: 'center' },
  captureBtnInner: { width: 54, height: 54, borderRadius: 27, backgroundColor: '#fff' },

  // Scores
  scoresRow: { flexDirection: 'row', marginHorizontal: 16, marginTop: 16, gap: 10, flexWrap: 'wrap' },
  scoreCard: { backgroundColor: '#FFFFFF', borderRadius: 12, padding: 14, alignItems: 'center', borderWidth: 2, minWidth: 90, shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05, shadowRadius: 2, elevation: 1 },
  scoreGrade: { fontSize: 28, fontWeight: '900' },
  scoreLabel: { color: '#64748B', fontSize: 11, marginTop: 2 },

  aiButtonContainer: { marginHorizontal: 16, marginTop: 20, shadowColor: '#006EB7', shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.2, shadowRadius: 6, elevation: 3 },
  aiButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10, paddingVertical: 14, borderRadius: 14 },
  aiButtonText: { color: '#fff', fontSize: 16, fontWeight: '700' },

  // Sections
  section: { marginHorizontal: 16, marginTop: 24 },
  sectionTitle: { fontSize: 16, fontWeight: '700', color: '#1E293B', marginBottom: 12 },
  sectionSubtitle: { color: '#64748B', fontSize: 13, marginTop: -8, marginBottom: 14 },

  originTags: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  originTag: { backgroundColor: '#E0F2FE', borderRadius: 20, paddingHorizontal: 14, paddingVertical: 6, borderWidth: 1, borderColor: '#BAE6FD' },
  originTagText: { color: '#006EB7', fontSize: 13, fontWeight: '600' },

  infoBox: { backgroundColor: '#FFFFFF', borderRadius: 10, padding: 14, flexDirection: 'row', alignItems: 'center', gap: 10, borderWidth: 1, borderColor: '#E2E8F0', shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05, shadowRadius: 2, elevation: 1 },
  infoText: { color: '#334155', fontSize: 14, flex: 1 },

  // Carbon
  carbonCard: { backgroundColor: '#FFFFFF', borderRadius: 14, padding: 16, borderWidth: 1.5, shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05, shadowRadius: 2, elevation: 1 },
  carbonHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 },
  carbonTotal: { fontSize: 26, fontWeight: '900' },
  carbonPer: { color: '#64748B', fontSize: 12, marginTop: 2 },
  carbonGradeBadge: { borderRadius: 10, padding: 10, alignItems: 'center', borderWidth: 1.5, minWidth: 80 },
  carbonGradeText: { fontSize: 22, fontWeight: '900' },
  carbonGradeLabel: { fontSize: 11, fontWeight: '600', textAlign: 'center', marginTop: 2 },
  carbonContributors: { borderTopWidth: 1, borderTopColor: '#E2E8F0', paddingTop: 12 },
  carbonContribTitle: { color: '#64748B', fontSize: 12, marginBottom: 8 },
  carbonContribRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 6 },
  carbonContribName: { color: '#334155', fontSize: 13 },
  carbonContribVal: { color: '#0F172A', fontSize: 13, fontWeight: '600' },

  // World summary
  worldSummary: { backgroundColor: '#F0F9FF', borderRadius: 10, padding: 14, marginBottom: 16, borderWidth: 1, borderColor: '#BAE6FD' },
  worldSummaryText: { color: '#334155', fontSize: 14, textAlign: 'center' },
  highlight: { color: '#006EB7', fontWeight: '700' },

  // Ingredient cards
  ingredientCard: { backgroundColor: '#FFFFFF', borderRadius: 14, padding: 16, marginBottom: 12, borderWidth: 1, borderColor: '#E2E8F0', shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05, shadowRadius: 3, elevation: 1 },
  ingredientHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 8 },
  ingredientName: { color: '#1E293B', fontSize: 15, fontWeight: '700', flex: 1 },
  ingredientNameDE: { color: '#006EB7', fontSize: 12, fontWeight: '600' },
  originDescription: { color: '#64748B', fontSize: 12, marginBottom: 10, lineHeight: 18 },
  countryList: { gap: 8 },
  countryRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  countryFlag: { fontSize: 20 },
  countryInfo: { width: 120 },
  countryName: { color: '#334155', fontSize: 13, fontWeight: '600' },
  countryRegion: { color: '#64748B', fontSize: 11 },
  percentageBar: { flex: 1, height: 6, backgroundColor: '#E2E8F0', borderRadius: 3, overflow: 'hidden' },
  percentageFill: { height: '100%', borderRadius: 3 },
  percentageText: { color: '#64748B', fontSize: 12, width: 35, textAlign: 'right' },
  noOriginRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  noOriginText: { color: '#64748B', fontSize: 13 },
  showMoreBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#F8FAFC', borderRadius: 10, padding: 12, gap: 6, marginTop: 4, borderWidth: 1, borderColor: '#E2E8F0' },
  showMoreText: { color: '#006EB7', fontSize: 14, fontWeight: '600' },

  // Shelf life
  shelfCard: { backgroundColor: '#FFFFFF', borderRadius: 14, padding: 16, borderWidth: 1.5, shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05, shadowRadius: 2, elevation: 1 },
  shelfRow: { flexDirection: 'row', alignItems: 'center', gap: 14, marginBottom: 12 },
  shelfIcon: { fontSize: 32 },
  shelfInfo: { flex: 1 },
  shelfDays: { fontSize: 22, fontWeight: '800' },
  shelfLabel: { color: '#64748B', fontSize: 12, marginTop: 2 },
  shelfTipRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 8, backgroundColor: '#FEF3C7', borderRadius: 8, padding: 10, borderWidth: 1, borderColor: '#FDE68A' },
  shelfTip: { color: '#92400E', fontSize: 13, flex: 1, lineHeight: 18 },

  // Nutrition
  nutritionGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  nutritionItem: { backgroundColor: '#FFFFFF', borderRadius: 12, padding: 14, width: '30%', flexGrow: 1, alignItems: 'center', borderWidth: 1, borderColor: '#E2E8F0', shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05, shadowRadius: 2, elevation: 1 },
  nutritionValue: { color: '#1E293B', fontSize: 18, fontWeight: '800' },
  nutritionUnit: { fontSize: 12, fontWeight: '400', color: '#64748B' },
  nutritionLabel: { color: '#64748B', fontSize: 11, marginTop: 4, textAlign: 'center' },

  // Price breakdown
  priceCard: { backgroundColor: '#FFFFFF', borderRadius: 14, padding: 16, borderWidth: 1, borderColor: '#E2E8F0', shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05, shadowRadius: 2, elevation: 1 },
  priceBarContainer: { flexDirection: 'row', height: 16, borderRadius: 8, overflow: 'hidden', marginBottom: 16 },
  priceBarSegment: { height: '100%' },
  priceLegendRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 8 },
  priceLegendDot: { width: 10, height: 10, borderRadius: 5 },
  priceLegendLabel: { color: '#334155', fontSize: 13, flex: 1 },
  priceLegendPct: { fontSize: 13, fontWeight: '700', color: '#1E293B' },

  // Pantry Button
  pantryButtonContainer: { marginHorizontal: 16, marginTop: 12 },
  pantryButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10, paddingVertical: 14, borderRadius: 14, borderWidth: 1.5, borderColor: '#006EB7', backgroundColor: '#fff' },
  pantryButtonText: { color: '#006EB7', fontSize: 16, fontWeight: '700' },

  // Map
  mapWrapper: { height: 200, marginVertical: 16, borderRadius: 12, overflow: 'hidden', borderWidth: 1, borderColor: '#E2E8F0' },
  map: { flex: 1 },
  mapMarker: { backgroundColor: '#fff', borderRadius: 15, width: 30, height: 30, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#7C3AED', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.2, shadowRadius: 2, elevation: 3 },
  mapMarkerIcon: { fontSize: 14 },
  crowdInteraction: { flexDirection: 'row', gap: 10, marginTop: 16, borderTopWidth: 1, borderTopColor: '#F1F5F9', paddingTop: 16 },
  confirmBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, backgroundColor: '#ECFDF5', paddingVertical: 10, borderRadius: 10, borderWidth: 1, borderColor: '#10B981' },
  confirmText: { color: '#059669', fontSize: 13, fontWeight: '700' },
  reportBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, backgroundColor: '#FEF2F2', paddingVertical: 10, borderRadius: 10, borderWidth: 1, borderColor: '#EF4444' },
  reportText: { color: '#B91C1C', fontSize: 13, fontWeight: '700' },
});
